# Generated by Django 2.2.2 on 2019-07-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_model',
            name='deployed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
