# Generated by Django 2.2.2 on 2019-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_parameter', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('second_parameter', models.IntegerField()),
            ],
        ),
    ]
