# Generated by Django 2.2.2 on 2019-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='conditions',
        ),
    ]
