# Generated by Django 2.2.2 on 2019-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_auto_20190625_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
