# Generated by Django 2.2.2 on 2019-07-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_entry_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entry_data',
            new_name='conditions',
        ),
    ]
